import React, { useState } from "react";
import { Sparkles, Coins, ArrowRight, ShieldAlert, HelpCircle, Laptop, Landmark } from "lucide-react";

interface Props {
  onSignalGenerated: (signalData: {
    assetClass: string;
    symbol: string;
    action: string;
    entry: string;
    tp1: string;
    tp2: string;
    tp3: string;
    sl: string;
    formattedText: string;
    rationale: string;
  }) => void;
  aiConfigured: boolean;
}

export default function TradingSignalForm({ onSignalGenerated, aiConfigured }: Props) {
  // Toggle tab: "classic" vs "deriv"
  const [formMode, setFormMode] = useState<"classic" | "deriv">("deriv");

  // --- COMMON OR CLASSIC MODE STATE ---
  const [assetClass, setAssetClass] = useState("Forex");
  const [symbol, setSymbol] = useState("GBPUSD");
  const [action, setAction] = useState("BUY");
  const [entry, setEntry] = useState("");
  const [tp1, setTp1] = useState("");
  const [tp2, setTp2] = useState("");
  const [tp3, setTp3] = useState("");
  const [sl, setSl] = useState("");
  const [userNotes, setUserNotes] = useState("");
  const [sentiment, setSentiment] = useState("Moderate");

  // --- DERIV SYNTHETIC DIGIT MODE STATE ---
  const [derivSymbol, setDerivSymbol] = useState("VOLATILITY 100 (1s) INDEX");
  const [derivAction, setDerivAction] = useState("UNDER 7");
  const [derivStrategy, setDerivStrategy] = useState("Second Least Digit");
  const [derivTicks, setDerivTicks] = useState("1ticks");
  const [derivBotName, setDerivBotName] = useState("USE SNIPPER KILLER BOT");
  const [derivEntryDigit, setDerivEntryDigit] = useState("9");
  const [derivConfidence, setDerivConfidence] = useState("85%");
  const [derivPromoUrl, setDerivPromoUrl] = useState("https://mrzetuzetu.site");
  const [derivRiskManagement, setDerivRiskManagement] = useState(
    "• Stop after 4 consecutive wins\n• Max 5 runs per session\n• Use proper recovery if loss occurs"
  );
  const [derivBotSignature, setDerivBotSignature] = useState("mrzetuzetu Over/Under Bot");
  const [derivHashtags, setDerivHashtags] = useState("#TradingSignal #Deriv #OverUnder");

  const [generating, setGenerating] = useState(false);
  const [genError, setGenError] = useState("");

  const handleManualFormat = () => {
    if (formMode === "deriv") {
      // Create exact format as requested for Deriv Digits
      let html = `<b>🔔 NEW TRADING SIGNAL 🔔</b>\n\n`;
      html += `<b>${derivSymbol.toUpperCase()}</b>\n\n`;
      html += `📈 <b>${derivAction.toUpperCase()}</b>\n`;
      html += `⚡ <b>Strategy:</b> ${derivStrategy}\n\n`;
      html += `📊 <b>Market Analysis (${derivTicks})</b>\n`;
      html += `━━━━━━━━━\n`;
      html += `🎯 <b>Entry Instructions:</b>\n\n`;
      html += `<b>${derivBotName.toUpperCase()}</b>\n`;
      html += `💹 <b>Trade:</b> ${derivAction}\n`;
      html += `🔑 <b>Entry Digit:</b> <code>${derivEntryDigit}</code>\n`;
      html += `⭐ <b>Confidence:</b> ${derivConfidence}\n\n`;
      if (derivPromoUrl) {
         html += `${derivPromoUrl}\n\n`;
      }
      html += `📈 <b>Session Stats:</b>\n\n`;
      html += `⚠️ <b>Risk Management:</b>\n`;
      html += `${derivRiskManagement}\n\n`;
      
      const now = new Date();
      // Format like: "6/4/26, 6:20:07 PM UTC"
      const timeStr = `${now.getMonth() + 1}/${now.getDate()}/${String(now.getFullYear()).substring(2)}, ${now.toLocaleTimeString("en-US")} UTC`;
      html += `⏰ <b>Time:</b> ${timeStr}\n\n`;
      html += `🤖 Generated by ${derivBotSignature}\n`;
      html += `${derivHashtags}`;

      const textNotes = userNotes || `Deriv digit contract on ${derivSymbol} using ${derivStrategy}. Duration: ${derivTicks}.`;

      onSignalGenerated({
        assetClass: "Deriv Synthetic",
        symbol: derivSymbol,
        action: derivAction,
        entry: `Digit ${derivEntryDigit}`,
        tp1: `LDP: ${derivAction}`,
        tp2: "",
        tp3: "",
        sl: `Confidence: ${derivConfidence}`,
        formattedText: html,
        rationale: `<b>Under/Over Contract Logic:</b> This synthetic contract leverages digit pattern frequency on ${derivSymbol} across ${derivTicks}. Specifically executing a custom contract based on '${derivStrategy}' when digit trigger '${derivEntryDigit}' prints on tick history. Optimal execution requires automated triggers like '${derivBotName}' with confidence predicted at ${derivConfidence}. Notes: ${textNotes}`,
      });
    } else {
      // Classic mode manual formatting
      const directionEmoji = action.includes("BUY") ? "🟢 BUY" : "🔴 SELL";
      const titleDir = action.toUpperCase();

      let html = `<b>📣 NEW TRADING SIGNAL: ${symbol.toUpperCase()}</b>\n`;
      html += `━━━━━━━━━━━━━━━━━━━━━━\n`;
      html += `<b>Direction:</b> ${directionEmoji} [${titleDir}]\n`;
      html += `<b>Entry Zone:</b> ${entry ? `<code>${entry}</code>` : "Current Market Price"}\n\n`;

      if (tp1) html += `🎯 <b>Take Profit 1:</b> <code>${tp1}</code>\n`;
      if (tp2) html += `🎯 <b>Take Profit 2:</b> <code>${tp2}</code>\n`;
      if (tp3) html += `🎯 <b>Take Profit 3:</b> <code>${tp3}</code>\n`;
      if (sl) html += `\n🛡️ <b>Stop Loss:</b> <code>${sl}</code>\n`;

      if (userNotes) {
        html += `\n📝 <b>Analysis Brief:</b>\n<i>${userNotes}</i>\n`;
      }

      html += `━━━━━━━━━━━━━━━━━━━━━━\n`;
      html += `⚠️ <i>Trade with proper risk controls only! Risk sentiment: ${sentiment}</i>`;

      const simpleRationale = userNotes || `Technical setup configured for a ${action} trade on ${symbol.toUpperCase()} entering near ${entry || "current rates"} with Risk model: ${sentiment}.`;

      onSignalGenerated({
        assetClass,
        symbol: symbol.toUpperCase(),
        action,
        entry,
        tp1,
        tp2,
        tp3,
        sl,
        formattedText: html,
        rationale: simpleRationale,
      });
    }
  };

  const handleGeminiFormat = async (e: React.FormEvent) => {
    e.preventDefault();
    setGenerating(true);
    setGenError("");

    try {
      let bodyData: Record<string, any> = {};

      if (formMode === "deriv") {
        bodyData = {
          assetClass: "Deriv Synthetic",
          symbol: derivSymbol.toUpperCase(),
          action: derivAction,
          entry: `Digit ${derivEntryDigit}`,
          sl: `Confidence: ${derivConfidence}`,
          userNotes,
          sentiment,
          isDerivStyle: true,
          strategyName: derivStrategy,
          ticksCount: derivTicks,
          botName: derivBotName,
          entryDigit: derivEntryDigit,
          confidence: derivConfidence,
          promoUrl: derivPromoUrl,
          riskGuidelines: derivRiskManagement,
          botSignature: derivBotSignature,
          hashtags: derivHashtags,
        };
      } else {
        bodyData = {
          assetClass,
          symbol: symbol.toUpperCase(),
          action,
          entry,
          tp: [tp1, tp2, tp3].filter(Boolean),
          sl,
          userNotes,
          sentiment,
          isDerivStyle: false,
        };
      }

      const response = await fetch("/api/gemini/generate-signal", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify(bodyData),
      });

      const data = await response.json();
      if (!response.ok || data.error) {
        throw new Error(data.error || "Generation payload failed.");
      }

      if (formMode === "deriv") {
        onSignalGenerated({
          assetClass: "Deriv Synthetic",
          symbol: derivSymbol.toUpperCase(),
          action: derivAction,
          entry: `Digit ${derivEntryDigit}`,
          tp1: derivAction,
          tp2: "",
          tp3: "",
          sl: `Confidence: ${derivConfidence}`,
          formattedText: data.signal,
          rationale: data.rationale,
        });
      } else {
        onSignalGenerated({
          assetClass,
          symbol: symbol.toUpperCase(),
          action,
          entry,
          tp1,
          tp2,
          tp3,
          sl,
          formattedText: data.signal,
          rationale: data.rationale,
        });
      }
    } catch (err: any) {
      setGenError(err.message || "Failed to generate design composition using Gemini AI. Using format engine fallback.");
      handleManualFormat();
    } finally {
      setGenerating(false);
    }
  };

  const loadExample = (type: "deriv_under" | "deriv_odds" | "forex" | "crypto") => {
    if (type === "deriv_under") {
      setFormMode("deriv");
      setDerivSymbol("VOLATILITY 100 (1s) INDEX");
      setDerivAction("UNDER 7");
      setDerivStrategy("Second Least Digit");
      setDerivTicks("1ticks");
      setDerivBotName("USE SNIPPER KILLER BOT");
      setDerivEntryDigit("9");
      setDerivConfidence("85%");
      setDerivPromoUrl("https://mrzetuzetu.site");
      setDerivRiskManagement("• Stop after 4 consecutive wins\n• Max 5 runs per session\n• Use proper recovery if loss occurs");
      setDerivBotSignature("mrzetuzetu Over/Under Bot");
      setDerivHashtags("#TradingSignal #Deriv #OverUnder");
    } else if (type === "deriv_odds") {
      setFormMode("deriv");
      setDerivSymbol("VOLATILITY 75 INDEX");
      setDerivAction("OVER 5");
      setDerivStrategy("Tick Oscillator Breakout");
      setDerivTicks("5ticks");
      setDerivBotName("USE DERIV SNIPER BOT v4");
      setDerivEntryDigit("2");
      setDerivConfidence("92%");
      setDerivPromoUrl("https://mrzetuzetu.site");
      setDerivRiskManagement("• Target maximum 3 sessions per day\n• Set stake at 1% of total bank capital\n• Pause immediately on trade loss");
      setDerivBotSignature("mrzetuzetu Premium Ticks Bot");
      setDerivHashtags("#VolatilityIdx #DerivDigits #OverUnder");
    } else if (type === "crypto") {
      setFormMode("classic");
      setAssetClass("Crypto");
      setSymbol("BTCUSD");
      setAction("BUY LIMIT");
      setEntry("67400");
      setTp1("68900");
      setTp2("70200");
      setTp3("72000");
      setSl("66100");
      setUserNotes("4h RSI showing strong oversold divergence. Support trendline holds firmly.");
      setSentiment("Aggressive");
    } else {
      setFormMode("classic");
      setAssetClass("Forex");
      setSymbol("GBPUSD");
      setAction("SELL");
      setEntry("1.2650");
      setTp1("1.2590");
      setTp2("1.2520");
      setTp3("1.2450");
      setSl("1.2715");
      setUserNotes("Double top reversal pattern on Daily chart. UK CPI news expected to be cooler.");
      setSentiment("Moderate");
    }
  };

  return (
    <div className="bg-slate-900 border border-slate-800 rounded-2xl p-6 shadow-xl space-y-6 animate-fade-in" id="signal-builder-card">
      <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-4 border-b border-slate-800/80 pb-4">
        <div className="space-y-1">
          <h2 className="text-lg font-semibold tracking-tight text-white font-sans flex items-center gap-2">
            <Coins className="w-5 h-5 text-sky-450" />
            <span>Signal Builder Studio</span>
          </h2>
          <p className="text-xs text-slate-400">Select model layout guidelines and feed signal metrics.</p>
        </div>

        {/* Preset list */}
        <div className="flex flex-wrap items-center gap-2" id="preset-buttons">
          <span className="text-[10px] uppercase tracking-wider text-slate-500 font-bold font-sans">Template presets:</span>
          {formMode === "deriv" ? (
            <>
              <button
                type="button"
                onClick={() => loadExample("deriv_under")}
                className="text-[10px] px-2.5 py-1.5 bg-sky-950/40 border border-sky-900/60 text-sky-300 rounded-lg hover:text-white transition-all cursor-pointer"
              >
                Deriv Under 7
              </button>
              <button
                type="button"
                onClick={() => loadExample("deriv_odds")}
                className="text-[10px] px-2.5 py-1.5 bg-slate-850 text-slate-350 border border-slate-800 hover:border-slate-700/60 rounded-lg hover:text-white transition-all cursor-pointer"
              >
                Deriv Over 5
              </button>
            </>
          ) : (
            <>
              <button
                type="button"
                onClick={() => loadExample("forex")}
                className="text-[10px] px-2.5 py-1.5 bg-slate-850 text-slate-350 border border-slate-800 hover:border-slate-700/60 rounded-lg hover:text-white transition-all cursor-pointer animate-fade-in"
              >
                Forex standard
              </button>
              <button
                type="button"
                onClick={() => loadExample("crypto")}
                className="text-[10px] px-2.5 py-1.5 bg-slate-850 text-slate-350 border border-slate-800 hover:border-slate-700/60 rounded-lg hover:text-white transition-all cursor-pointer"
              >
                Crypto standard
              </button>
            </>
          )}
        </div>
      </div>

      {/* Signal Type Selector (Tabs) */}
      <div className="grid grid-cols-2 gap-2 bg-slate-950 p-1 border border-slate-850 rounded-xl" id="profile-selector-tabs">
        <button
          type="button"
          onClick={() => {
            setFormMode("deriv");
            // Default Deriv options loaded
            setDerivSymbol("VOLATILITY 100 (1s) INDEX");
            setDerivAction("UNDER 7");
          }}
          className={`py-2 px-3 text-xs font-semibold rounded-lg flex items-center justify-center gap-2 transition-all cursor-pointer ${
            formMode === "deriv"
              ? "bg-slate-800 text-white shadow"
              : "text-slate-400 hover:text-slate-200"
          }`}
          id="btn-choose-deriv-mode"
        >
          <Laptop className="w-3.5 h-3.5" />
          <span>Deriv Synthetic (Digits Bot Style)</span>
        </button>

        <button
          type="button"
          onClick={() => {
            setFormMode("classic");
          }}
          className={`py-2 px-3 text-xs font-semibold rounded-lg flex items-center justify-center gap-2 transition-all cursor-pointer ${
            formMode === "classic"
              ? "bg-slate-800 text-white shadow"
              : "text-slate-400 hover:text-slate-200"
          }`}
          id="btn-choose-classic-mode"
        >
          <Landmark className="w-3.5 h-3.5" />
          <span>Forex & Crypto (Standard MT4 Style)</span>
        </button>
      </div>

      <form onSubmit={handleGeminiFormat} className="space-y-4">
        {formMode === "deriv" ? (
          /* DERIV ACTIVE FORM FIELD CODES */
          <div className="space-y-4" id="deriv-form-fields">
            
            <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
              {/* Asset Index Name */}
              <div className="space-y-1.5">
                <label className="text-xs font-medium text-slate-300">Volatility Index Asset</label>
                <select
                  value={derivSymbol}
                  onChange={(e) => setDerivSymbol(e.target.value)}
                  className="w-full px-3 py-2 text-xs bg-slate-950 border border-slate-800 focus:border-sky-500 rounded-xl text-slate-300 focus:text-white outline-none transition-all cursor-pointer"
                  id="deriv-symbol-select"
                >
                  <option value="VOLATILITY 100 (1s) INDEX">Volatility 100 (1s) Index</option>
                  <option value="VOLATILITY 100 INDEX">Volatility 100 Index</option>
                  <option value="VOLATILITY 75 (1s) INDEX">Volatility 75 (1s) Index</option>
                  <option value="VOLATILITY 75 INDEX">Volatility 75 Index</option>
                  <option value="VOLATILITY 50 INDEX">Volatility 50 Index</option>
                  <option value="VOLATILITY 25 INDEX">Volatility 25 Index</option>
                  <option value="VOLATILITY 10 INDEX">Volatility 10 Index</option>
                  <option value="JUMP 100 INDEX">Jump 100 Index</option>
                  <option value="JUMP 50 INDEX">Jump 50 Index</option>
                  <option value="BEAR MARKET INDEX">Bear Market Index</option>
                  <option value="BULL MARKET INDEX">Bull Market Index</option>
                </select>
                <div className="pt-1">
                  <input
                    type="text"
                    value={derivSymbol}
                    onChange={(e) => setDerivSymbol(e.target.value)}
                    placeholder="Or type custom synthetic name..."
                    className="w-full px-3 py-1.5 text-[11px] bg-slate-950 border border-slate-800 focus:border-sky-500 rounded-lg text-slate-300 font-mono"
                    id="deriv-symbol-custom-input"
                  />
                </div>
              </div>

              {/* Trade action Contract */}
              <div className="space-y-1.5">
                <label className="text-xs font-medium text-slate-300">Trade / Contract Type</label>
                <input
                  type="text"
                  value={derivAction}
                  onChange={(e) => setDerivAction(e.target.value)}
                  placeholder="e.g. UNDER 7, OVER 5, MATCHES 9, DIFFERS 2"
                  className="w-full px-3 py-2.5 text-xs bg-slate-950 border border-slate-800 focus:border-sky-500 rounded-xl text-slate-100 placeholder-slate-650 outline-none font-bold text-sky-400 font-mono tracking-wider"
                  required
                  id="deriv-action-input"
                />
                <span className="text-[10px] text-slate-500 block">Typical formats: UNDER 7, OVER 5, MATCHES 9, DIFFERS 0</span>
              </div>
            </div>

            <div className="grid grid-cols-1 md:grid-cols-3 gap-4">
              {/* Strategy Name */}
              <div className="space-y-1.5">
                <label className="text-xs font-medium text-slate-300">Strategy Name</label>
                <input
                  type="text"
                  value={derivStrategy}
                  onChange={(e) => setDerivStrategy(e.target.value)}
                  placeholder="e.g. Second Least Digit"
                  className="w-full px-3 py-2 text-xs bg-slate-950 border border-slate-800 focus:border-sky-500 rounded-xl text-slate-100 placeholder-slate-650 outline-none"
                  id="deriv-strategy-input"
                />
              </div>

              {/* Ticks Duration */}
              <div className="space-y-1.5">
                <label className="text-xs font-medium text-slate-300">Ticks Duration</label>
                <select
                  value={derivTicks}
                  onChange={(e) => setDerivTicks(e.target.value)}
                  className="w-full px-3 py-2 text-xs bg-slate-950 border border-slate-800 focus:border-sky-500 rounded-xl text-slate-300 focus:text-white outline-none transition-all cursor-pointer font-mono"
                  id="deriv-ticks-select"
                >
                  <option value="1ticks">1 Ticks</option>
                  <option value="2ticks">2 Ticks</option>
                  <option value="3ticks">3 Ticks</option>
                  <option value="5ticks">5 Ticks</option>
                  <option value="10ticks">10 Ticks</option>
                </select>
              </div>

              {/* Trigger Entry Digit */}
              <div className="space-y-1.5">
                <label className="text-xs font-medium text-slate-300">Key Trigger Entry Digit</label>
                <input
                  type="text"
                  value={derivEntryDigit}
                  onChange={(e) => setDerivEntryDigit(e.target.value)}
                  placeholder="e.g. 9"
                  className="w-full px-3 py-2 text-xs bg-slate-950 border border-slate-800 focus:border-sky-500 rounded-xl text-slate-100 placeholder-slate-650 outline-none font-mono text-center"
                  id="deriv-entry-digit-input"
                />
              </div>
            </div>

            <div className="grid grid-cols-1 md:grid-cols-3 gap-4">
              {/* Snipper Bot recommendation code */}
              <div className="space-y-1.5">
                <label className="text-xs font-medium text-slate-300">Execution Bot System</label>
                <input
                  type="text"
                  value={derivBotName}
                  onChange={(e) => setDerivBotName(e.target.value)}
                  placeholder="e.g. USE SNIPPER KILLER BOT"
                  className="w-full px-3 py-2 text-xs bg-slate-950 border border-slate-800 focus:border-sky-500 rounded-xl text-slate-100 placeholder-slate-650 outline-none font-semibold text-yellow-300"
                  id="deriv-bot-name-input"
                />
              </div>

              {/* Confidence rate */}
              <div className="space-y-1.5">
                <label className="text-xs font-medium text-slate-300">Historical Confidence %</label>
                <input
                  type="text"
                  value={derivConfidence}
                  onChange={(e) => setDerivConfidence(e.target.value)}
                  placeholder="e.g. 85%"
                  className="w-full px-3 py-2 text-xs bg-slate-950 border border-slate-800 focus:border-sky-500 rounded-xl text-emerald-400 placeholder-slate-650 outline-none text-center font-bold"
                  id="deriv-confidence-input"
                />
              </div>

              {/* Redirection url */}
              <div className="space-y-1.5">
                <label className="text-xs font-medium text-slate-300">Promotional Site / Redirect link</label>
                <input
                  type="url"
                  value={derivPromoUrl}
                  onChange={(e) => setDerivPromoUrl(e.target.value)}
                  placeholder="e.g. https://mrzetuzetu.site"
                  className="w-full px-3 py-2 text-xs bg-slate-950 border border-slate-800 focus:border-sky-500 rounded-xl text-slate-350 placeholder-slate-650 outline-none font-mono"
                  id="deriv-promo-url-input"
                />
              </div>
            </div>

            {/* Risk Management multiline */}
            <div className="space-y-1.5">
              <label className="text-xs font-medium text-slate-300">Risk Management Guidelines (Lines)</label>
              <textarea
                value={derivRiskManagement}
                onChange={(e) => setDerivRiskManagement(e.target.value)}
                rows={3}
                placeholder="• Stop after 4 consecutive wins..."
                className="w-full p-3 text-xs bg-slate-950 border border-slate-800 focus:border-sky-500 rounded-xl text-amber-300 font-mono outline-none resize-none"
                id="deriv-risk-instructions"
              />
            </div>

            {/* Signature & Hashtags */}
            <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
              <div className="space-y-1.5">
                <label className="text-xs font-medium text-slate-300">Footer Signature Brand</label>
                <input
                  type="text"
                  value={derivBotSignature}
                  onChange={(e) => setDerivBotSignature(e.target.value)}
                  placeholder="e.g. mrzetuzetu Over/Under Bot"
                  className="w-full px-3 py-2 text-xs bg-slate-950 border border-slate-800 focus:border-sky-500 rounded-xl text-slate-100 outline-none"
                  id="deriv-signature-input"
                />
              </div>
              
              <div className="space-y-1.5">
                <label className="text-xs font-medium text-slate-300">Social Channel Hashtags</label>
                <input
                  type="text"
                  value={derivHashtags}
                  onChange={(e) => setDerivHashtags(e.target.value)}
                  placeholder="#TradingSignal #Deriv #OverUnder"
                  className="w-full px-3 py-2 text-xs bg-slate-950 border border-slate-800 focus:border-sky-500 rounded-xl text-slate-400 placeholder-slate-650 outline-none font-mono"
                  id="deriv-hashtags-input"
                />
              </div>
            </div>

          </div>
        ) : (
          /* CLASSIC FOREX / CRYPTO FORM FIELDS */
          <div className="space-y-4 animate-fade-in" id="classic-form-fields">
            <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
              {/* Asset Category */}
              <div className="space-y-1.5">
                <label className="text-xs font-medium text-slate-300">Asset Class</label>
                <select
                  value={assetClass}
                  onChange={(e) => setAssetClass(e.target.value)}
                  className="w-full px-3 py-2 text-xs bg-slate-950 border border-slate-800 focus:border-sky-500 rounded-xl text-slate-300 focus:text-white outline-none transition-all cursor-pointer"
                  id="select-asset-class"
                >
                  <option value="Forex">Forex</option>
                  <option value="Crypto">Crypto</option>
                  <option value="Stocks">Stocks / Equities</option>
                  <option value="Indices">Indices (US30, NAS100)</option>
                  <option value="Commodities">Commodities (GOLD, OIL)</option>
                </select>
              </div>

              {/* Symbol */}
              <div className="space-y-1.5">
                <label className="text-xs font-medium text-slate-300">Asset Symbol</label>
                <input
                  type="text"
                  value={symbol}
                  onChange={(e) => setSymbol(e.target.value)}
                  placeholder="e.g. EURUSD, BTCUSD, XAUUSD"
                  className="w-full px-3 py-2 text-xs bg-slate-950 border border-slate-800 focus:border-sky-500 rounded-xl text-slate-100 placeholder-slate-650 outline-none uppercase font-mono tracking-wider"
                  required
                  id="input-asset-symbol"
                />
              </div>
            </div>

            <div className="grid grid-cols-1 md:grid-cols-3 gap-4">
              {/* Order Type */}
              <div className="space-y-1.5 font-sans">
                <label className="text-xs font-medium text-slate-300">Direction / Order Type</label>
                <select
                  value={action}
                  onChange={(e) => setAction(e.target.value)}
                  className="w-full px-3 py-2 text-xs bg-slate-950 border border-slate-800 focus:border-sky-500 rounded-xl text-slate-300 focus:text-white outline-none transition-all cursor-pointer"
                  id="select-direction-action"
                >
                  <option value="BUY">BUY (Market execution)</option>
                  <option value="SELL">SELL (Market execution)</option>
                  <option value="BUY LIMIT">BUY LIMIT</option>
                  <option value="SELL LIMIT">SELL LIMIT</option>
                  <option value="BUY STOP">BUY STOP</option>
                  <option value="SELL STOP">SELL STOP</option>
                </select>
              </div>

              {/* Entry price */}
              <div className="space-y-1.5">
                <label className="text-xs font-medium text-slate-300">Entry Price Zone</label>
                <input
                  type="text"
                  value={entry}
                  onChange={(e) => setEntry(e.target.value)}
                  placeholder="e.g. 1.0925 (or current rate)"
                  className="w-full px-3 py-2 text-xs bg-slate-950 border border-slate-800 focus:border-sky-500 rounded-xl text-slate-100 placeholder-slate-650 font-mono outline-none override-id"
                  id="input-entry-price"
                />
              </div>

              {/* Risk Sentiment model */}
              <div className="space-y-1.5">
                <label className="text-xs font-medium text-slate-300">Risk Profile</label>
                <select
                  value={sentiment}
                  onChange={(e) => setSentiment(e.target.value)}
                  className="w-full px-3 py-2 text-xs bg-slate-950 border border-slate-800 focus:border-sky-500 rounded-xl text-slate-300 focus:text-white outline-none transition-all cursor-pointer"
                  id="select-risk-sentiment"
                >
                  <option value="Conservative">Conservative (Low RR)</option>
                  <option value="Moderate">Moderate (Std 1:2 RR)</option>
                  <option value="Aggressive">Aggressive (High leverage)</option>
                </select>
              </div>
            </div>

            {/* Take profit threshold grid */}
            <div className="bg-slate-950/60 p-4 border border-slate-850 rounded-xl space-y-3.5">
              <div className="text-xs font-medium text-slate-200">Take Profit Thresholds</div>
              <div className="grid grid-cols-1 sm:grid-cols-3 gap-3">
                <div className="space-y-1">
                  <label className="text-[10px] uppercase font-semibold text-slate-500 font-sans">Take Profit 1</label>
                  <input
                    type="text"
                    value={tp1}
                    onChange={(e) => setTp1(e.target.value)}
                    placeholder="Target TP 1"
                    className="w-full px-3 py-1.5 text-xs bg-slate-900 border border-slate-800 focus:border-sky-500 rounded-lg text-emerald-400 placeholder-slate-600 font-mono text-center outline-none"
                    id="input-tp1"
                  />
                </div>
                <div className="space-y-1">
                  <label className="text-[10px] uppercase font-semibold text-slate-500 font-sans">Take Profit 2 (Optional)</label>
                  <input
                    type="text"
                    value={tp2}
                    onChange={(e) => setTp2(e.target.value)}
                    placeholder="Target TP 2"
                    className="w-full px-3 py-1.5 text-xs bg-slate-900 border border-slate-800 focus:border-sky-500 rounded-lg text-emerald-400 placeholder-slate-600 font-mono text-center outline-none"
                    id="input-tp2"
                  />
                </div>
                <div className="space-y-1">
                  <label className="text-[10px] uppercase font-semibold text-slate-500 font-sans">Take Profit 3 (Optional)</label>
                  <input
                    type="text"
                    value={tp3}
                    onChange={(e) => setTp3(e.target.value)}
                    placeholder="Target TP 3"
                    className="w-full px-3 py-1.5 text-xs bg-slate-900 border border-slate-800 focus:border-sky-500 rounded-lg text-emerald-400 placeholder-slate-600 font-mono text-center outline-none"
                    id="input-tp3"
                  />
                </div>
              </div>
            </div>

            {/* Stop Loss & Technical brief */}
            <div className="grid grid-cols-1 md:grid-cols-4 gap-4">
              <div className="space-y-1.5 md:col-span-1">
                <label className="text-xs font-medium text-slate-300">Stop Loss (SL)</label>
                <input
                  type="text"
                  value={sl}
                  onChange={(e) => setSl(e.target.value)}
                  placeholder="Stop level"
                  className="w-full px-3 py-2 text-xs bg-slate-950 border border-slate-800 focus:border-sky-500 rounded-xl text-rose-400 placeholder-slate-650 font-mono text-center outline-none"
                  id="input-stop-loss"
                />
              </div>

              <div className="space-y-1.5 md:col-span-3">
                <label className="text-xs font-medium text-slate-300">Technical Brief Notes</label>
                <input
                  type="text"
                  value={userNotes}
                  onChange={(e) => setUserNotes(e.target.value)}
                  placeholder="e.g. Double bottom on 4H chart, RSI trend breakout"
                  className="w-full px-3 py-2 text-xs bg-slate-950 border border-slate-800 focus:border-sky-500 rounded-xl text-slate-100 placeholder-slate-650 outline-none"
                  id="input-technical-brief-notes"
                />
              </div>
            </div>
          </div>
        )}

        {genError && (
          <div className="bg-rose-950/30 text-rose-300 border border-rose-900/50 rounded-xl p-3 text-xs flex items-center gap-2" id="builder-error-div">
            <ShieldAlert className="w-4 h-4 text-rose-400 shrink-0" />
            <span>{genError}</span>
          </div>
        )}

        {/* Action controllers */}
        <div className="flex flex-col sm:flex-row items-stretch sm:items-center gap-3 pt-3 border-t border-slate-800/60 font-sans">
          <button
            type="submit"
            disabled={generating}
            className="flex-1 bg-gradient-to-r from-sky-500 via-sky-600 to-indigo-600 hover:from-sky-400 hover:to-indigo-500 disabled:from-slate-800 disabled:to-slate-800 disabled:text-slate-500 text-white font-semibold text-xs py-3 px-5 rounded-xl flex items-center justify-center gap-2 shadow-lg shadow-sky-500/10 cursor-pointer disabled:cursor-not-allowed transform hover:-translate-y-px active:translate-y-0 transition-all font-sans"
            id="btn-gemini-draft-signal"
          >
            {generating ? (
              <>
                <svg className="animate-spin h-4 w-4 text-white" fill="none" viewBox="0 0 24 24">
                  <circle className="opacity-25" cx="12" cy="12" r="10" stroke="currentColor" strokeWidth="4" />
                  <path className="opacity-75" fill="currentColor" d="M4 12a8 8 0 018-8V0C5.373 0 0 5.373 0 12h4zm2 5.291A7.962 7.962 0 014 12H0c0 3.042 1.135 5.824 3 7.938l3-2.647z" />
                </svg>
                <span>AI is formulating signal message...</span>
              </>
            ) : (
              <>
                <Sparkles className="w-4 h-4 text-amber-300 fill-amber-300/20" />
                <span>AI Assist: Draft Signal & Rationale</span>
              </>
            )}
          </button>

          <button
            type="button"
            onClick={handleManualFormat}
            disabled={generating}
            className="px-5 py-3 text-xs border border-slate-850 hover:bg-slate-800/50 disabled:border-slate-850/45 disabled:text-slate-650 disabled:hover:bg-transparent text-slate-300 hover:text-white rounded-xl transition-all cursor-pointer font-sans"
            id="btn-manual-format-signal"
          >
            Compiler Mode (Format Instantly)
          </button>
        </div>
      </form>
    </div>
  );
}
